/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        app: {
          bg: '#0b0f14',
          card: '#121720',
          cardHover: '#181e29',
          border: 'rgba(255, 255, 255, 0.06)',
          textPrimary: '#ffffff',
          textSecondary: '#94a3b8',
        },
        accent: {
          cyan: '#06b6d4',
          purple: '#8b5cf6',
          pink: '#ec4899',
          orange: '#f59e0b',
          green: '#10b981',
          blue: '#3b82f6'
        },
        brand: {
          dark: '#0b0f19',
          card: '#111827',
          blue: '#3b82f6',
          purple: '#8b5cf6',
          green: '#10b981',
          text: '#9ca3af'
        },
        darkBg: '#0b0f19',
        darkPanel: 'rgba(15, 23, 42, 0.65)',
        accentViolet: '#8b5cf6',
        accentCyan: '#06b6d4',
        accentPink: '#ec4899',
        accentEmerald: '#10b981',
        "inverse-primary": "#006877",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#6900b3",
        "surface-container-high": "#272a2c",
        "on-tertiary": "#003824",
        "tertiary-container": "#46d89d",
        "secondary": "#ddb7ff",
        "surface-tint": "#2fd9f4",
        "surface": "#101415",
        "inverse-surface": "#e0e3e5",
        "on-tertiary-container": "#005a3d",
        "on-error": "#690005",
        "on-surface-variant": "#bbc9cd",
        "surface-container": "#1d2022",
        "outline-variant": "#3c494c",
        "secondary-fixed-dim": "#ddb7ff",
        "on-secondary": "#490080",
        "on-secondary-container": "#d6a9ff",
        "surface-variant": "#323537",
        "surface-container-lowest": "#0b0f10",
        "secondary-fixed": "#f0dbff",
        "tertiary": "#68f5b8",
        "surface-container-low": "#191c1e",
        "error": "#ffb4ab",
        "on-primary-fixed": "#001f25",
        "on-tertiary-fixed-variant": "#005236",
        "on-error-container": "#ffdad6",
        "primary-container": "#22d3ee",
        "surface-bright": "#363a3b",
        "primary-fixed-dim": "#2fd9f4",
        "primary-fixed": "#a2eeff",
        "on-primary-fixed-variant": "#004e5a",
        "error-container": "#93000a",
        "surface-container-highest": "#323537",
        "surface-dim": "#101415",
        "outline": "#859397",
        "on-background": "#e0e3e5",
        "on-primary-container": "#005763",
        "on-primary": "#00363e",
        "background": "#101415",
        "primary": "#8aebff",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#2c0051",
        "on-surface": "#e0e3e5",
        "secondary-container": "#6f00be",
        "inverse-on-surface": "#2d3133",
        "on-tertiary-fixed": "#002113"
      },
      fontFamily: {
        sans: ['Outfit', 'Inter', 'sans-serif'],
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 2.5s linear infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        }
      }
    },
  },
  plugins: [],
}
